SERVICE_NAME = "test-rust-service"
TIME_INTERVAL = 5
MESSAGE = "Time service running"
LOG_FILE_PATH = "/var/log/test-rust-service"
INSTALL_DIR = "/opt/rust-service"
CONFIG_DIR = "/etc/rust-service"
MEMORY_THRESHOLD = 80
DISK_THRESHOLD = 80
MIN_FD_LIMIT = 1024
MAX_SERVICE_NAME_LEN = 50
MAX_MESSAGE_LEN = 200
MAX_LOG_PATH_LEN = 255
MIN_LOG_INTERVAL_MS = 100
MAX_LOG_FILE_SIZE = 10485760
MAX_TIME_INTERVAL = 3600
MAX_THRESHOLD_PERCENT = 95
