SERVICE_NAME = "test-rust-service"
CONFIG_DIR = "/etc/test-rust-service"
LOG_FILE_PATH = "/var/log"
MEMORY_THRESHOLD = 80
DISK_THRESHOLD = 90
MIN_FD_LIMIT = 1024
MAX_SERVICE_NAME_LEN = 100
MAX_LOG_PATH_LEN = 255
MIN_LOG_INTERVAL_MS = 1000
MAX_LOG_FILE_SIZE = 10485760
MAX_TIME_INTERVAL = 86400
MAX_THRESHOLD_PERCENT = 100
MAX_FD_LIMIT = 65536
MAX_CONFIG_FIELD_LEN = 500

